### ISSUE TITLE
why do arm64 releases have the word "default." in them

### ISSUE THREAD

**Issue by anotherjesse** [replicate/yolo#13]
this makes the install instructions incorrect?

**Comment by zeke** [comment]
temporary workaround: https://github.com/anotherjesse/cog-sdxl-recur/blob/679b9b0c70221b9da0dbde4399d0a209975e75b5/Makefile#L4-L15

**Comment by zeke** [comment]
Maybe this is something configurable in https://github.com/goreleaser/goreleaser-action or https://github.com/goreleaser/goreleaser
